### ISSUE TITLE
New rust based firmware

### ISSUE THREAD

**Issue by filipton** [FKMTime/firmware#12]
Firwmare for esp32c3. [Pinout sheet](https://docs.google.com/spreadsheets/d/11cCbbXgz5qSA6mDK2ferCEzVc-j3fR25RjB6trtU-28/edit?usp=sharing).

### TODO:

- [x] Project setup (on new branch)
- [x] WIFI (with wifi manager)
- [x] MDNS search for micro-connector
- [x] Websocket connection to micro-connector
- [x] Ota updates via ws
- [x] Stackmat UART RX
- [x] Battery % measurement
- [x] Buttons handler
- [x] RFID scanner
- [x] Drive LCD Display
- [x] LCD with scenes (like in previous firmware) - maybe scene will be enum with displayed data as values to it?
- [x] FKM logic (all things as 2.X)
- [x] Drive 8segment big display
- [ ] Versioning
- [ ] Auto sleep (on new firmware - wait for new esp-hal and esp-wifi)
- [ ] Macros based translation system
   - From json file generate 2d array (first dimension - language, second dimension - translation)
   - Generate function to return index in array based on langauge and on translation_key (for example "en", "startup" -> (0, 0) )
   - Or better idea, convert all translations into single big string, and return from function offset in that string (would be faster and easier to encode in eeprom)
